version: "3"

services:
  serverless:
    platform: "linux/x86_64"
    build:
      context: ./docker/serverless
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/home/serverless/config/aws/credentials
    volumes:
      - ./:/home/serverless
    ports:
      - "3000:3000"
