service: serverless-lab

provider:
  name: aws
  endpointType: REGIONAL
  stage: ${opt:stage, 'local'}
  runtime: nodejs14.x
  region: sa-east-1
  versionFunctions: false
  # profile: default
  deploymentBucket:
    name: it-works-lab-serverless
  memorySize: 128
  timeout: 30
  environment: ${file(./config/env.${opt:stage}.yml)}

package:
  exclude:
    - "lib/phantomjs/phantomjs-linux"
    - "lib/phantomjs/phantomjs-mac"

functions:
  base64ToFile:
    handler: src/controllers/base64ToFile/index.handle
    environment:
      client: lab
      service: base64ToFile
    events:
      - http:
          path: base64ToFile
          method: POST

  downloadXML:
    handler: src/controllers/downloadXML/index.handle
    environment:
      client: lab
      service: downloadXML
    events:
      - http:
          path: downloadXML
          method: POST

custom:
  customDomain:
    basePath: "lab-${self:provider.stage}"
    stage: ${self:provider.stage}
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-offline
