service: serverless-lab

provider:
  name: aws
  endpointType: REGIONAL
  stage: ${opt:stage, 'local'}
  runtime: nodejs14.x
  region: sa-east-1
  versionFunctions: false
  # profile: default
  deploymentBucket:
    name: it-works-lab-serverless
  memorySize: 128
  timeout: 30
  environment: ${file(./config/env.${opt:stage}.yml)}

package:
  patterns:
    - "lib/phantomjs/phantomjs-linux"
    - "lib/phantomjs/phantomjs-mac"

functions:
  base64ToFile:
    handler: src/routes.base64ToFile
    environment:
      client: lab
      service: base64ToFile
    events:
      - http:
          path: base64ToFile
          method: POST

  downloadXML:
    handler: src/routes.downloadXML
    # disableLogs: true
    environment:
      client: lab
      service: downloadXML
    events:
      - http:
          path: downloadXML
          method: POST

  getFiles:
    handler: src/routes.getFiles
    environment:
      client: lab
      service: getFiles
    events:
      - http:
          path: getFiles
          method: POST

  uploadKeysNFe:
    handler: src/routes.uploadKeysNFe
    environment:
      client: lab
      service: uploadKeysNFe
    events:
      - http:
          path: uploadKeysNFe
          method: POST
          cors:
            allowedOrigins: "http://localhost:4200"
            # allowedOrigins: "https://app.impostograma.com.br"
            allowedHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, cnpj, type"
            allowedMethods: "*"

  uploadKeysNFeStatus:
    handler: src/routes.uploadKeysNFeStatus
    environment:
      client: lab
      service: uploadKeysNFeStatus
    events:
      - http:
          path: uploadKeysNFeStatus
          method: POST
          cors:
            allowedOrigins: "http://localhost:4200"
            # allowedOrigins: "https://app.impostograma.com.br"
            allowedHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, cnpj, type"
            allowedMethods: "*"

custom:
  customDomain:
    basePath: "lab-${self:provider.stage}"
    stage: ${self:provider.stage}
  serverless-offline:
    host: 0.0.0.0
    port: 3001

plugins:
  - serverless-offline
